/* Auto-generated by tribute-map/scripts/build_phase0_data.py. Do not edit by hand. */
(function (global) {
  "use strict";
  const NANJING = {
  "name": "应天府",
  "lat": 32.06,
  "lng": 118.78
};
  global.NANJING = NANJING;
  const MAP_CONFIG = {
  "bounds": {
    "latMin": -12,
    "latMax": 52,
    "lngMin": 73,
    "lngMax": 152
  },
  "projection": "equirectangular",
  "minSupportedWidth": 1024
};
  global.MAP_CONFIG = MAP_CONFIG;
  const ROUTE_TEMPLATES = {
  "sea_south": {
    "type": "sea_south",
    "name": "东南亚海路",
    "waypoints": [
      {
        "lat": 8.0,
        "lng": 109.0
      },
      {
        "lat": 18.5,
        "lng": 112.0
      },
      {
        "lat": 24.8,
        "lng": 118.6
      },
      {
        "lat": 30.0,
        "lng": 121.2
      }
    ]
  },
  "east_sea": {
    "type": "east_sea",
    "name": "东海路线",
    "waypoints": [
      {
        "lat": 27.0,
        "lng": 124.2
      },
      {
        "lat": 29.5,
        "lng": 122.0
      },
      {
        "lat": 31.0,
        "lng": 120.4
      }
    ]
  },
  "land_north": {
    "type": "land_north",
    "name": "陆路/混合路线",
    "waypoints": [
      {
        "lat": 40.0,
        "lng": 124.4
      },
      {
        "lat": 38.0,
        "lng": 121.5
      },
      {
        "lat": 35.5,
        "lng": 119.0
      }
    ]
  },
  "west_sea": {
    "type": "west_sea",
    "name": "西域/印度洋路线",
    "waypoints": [
      {
        "lat": 5.0,
        "lng": 95.0
      },
      {
        "lat": 9.0,
        "lng": 104.0
      },
      {
        "lat": 18.5,
        "lng": 112.0
      },
      {
        "lat": 24.8,
        "lng": 118.6
      },
      {
        "lat": 30.0,
        "lng": 121.2
      }
    ]
  }
};
  global.ROUTE_TEMPLATES = ROUTE_TEMPLATES;
  const TRIBUTE_COLORS = {
  "paper": "#F5F0E8",
  "ink": "#1A1008",
  "vermillion": "#C0392B",
  "goldBrown": "#8B6914",
  "land": "#E8E0D0",
  "coast": "#8B8070",
  "muted": "#B0A898"
};
  global.TRIBUTE_COLORS = TRIBUTE_COLORS;
  const TRIBUTE_CATEGORIES = {
  "animal": {
    "label": "动物",
    "icon": "elephant"
  },
  "spice": {
    "label": "香料",
    "icon": "incense"
  },
  "textile": {
    "label": "织物",
    "icon": "scroll"
  },
  "vessel": {
    "label": "器物",
    "icon": "vase"
  },
  "misc": {
    "label": "方物",
    "icon": "box"
  }
};
  global.TRIBUTE_CATEGORIES = TRIBUTE_CATEGORIES;
  if (typeof module !== "undefined" && module.exports) {
    module.exports = { NANJING, MAP_CONFIG, ROUTE_TEMPLATES, TRIBUTE_COLORS, TRIBUTE_CATEGORIES };
  }
})(typeof window !== "undefined" ? window : globalThis);
